// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhjvoviugkxiwlkrubmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoanZvdml1Z2t4aXdsa3J1Ym11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTIyOTUsImV4cCI6MjA2MTIyODI5NX0.ov9eOUmuLqGX7i1g82mdYHijVO-8yYy8haO_pd0HNjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);